#!/bin/bash 

runDir='/home/roger/Developer/saxpy'


runExe=("saxpy_variabled_openmp") 

numCores=("1" "2" "4" "8")

##if -e outputAllRuns rm outputAllRuns

outFile='output_compare.csv'
/bin/rm -f ${outFile}
/bin/touch ${outFile}
#echo ${outFile}
#echo "Program,		Number of Threads, 	Time,	GCalcs, GFlops" >> ${outFile}
## now loop through the above arrays
for runs in "${runExe[@]}"
do
	for num in "${numCores[@]}"
	do 
 	   export OMP_NUM_THREADS="$num"
 	  # echo -n $runs,	${OMP_NUM_THREADS},	>> ${outFile}
		#$runDir'/'$runs Control.dat | grep Wall | awk -F ' ' '{print $4 ", " $8 ", " $11}' >> ${outFile}

		$runDir'/'$runs  >> ${outFile}
	done
done


